MvcWebUI/Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Entities.Concrete;

namespace MvcWebUI.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillService _skillService;

        public SkillController(ISkillService skillService)
        {
            _skillService = skillService;
        }

        public IActionResult Index()
        {
            ViewBag.v1 = "Yetenek Listesi";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Listesi";
            var values = _skillService.TGetAll();
            return View(values.Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.v1 = "Yetenek Ekleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Ekleme";
            return View();
        }


        [HttpPost]
        public IActionResult Add(Skill skill)
        {
            _skillService.TAdd(skill);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var values = _skillService.TGetById(id);
            _skillService.TDelete(values.Data);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.v1 = "Yetenek Güncelleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Güncelleme";
            var values = _skillService.TGetById(id);
            return View(values.Data);

        }

        [HttpPost]
        public IActionResult Update(Skill skill)
        {
            _skillService.TUpdate(skill);
            return RedirectToAction("Index");

        }
    }
}

MvcWebUI/Views/Skill/Add.cshtml
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description" style="font-size: 18px">Yeni Yetenek Ekleme </p>


            <form class="form-group col-md-12" method="post">
                <div class="mb-3">
                    <label>Başlık</label>
                    <input type="text" name="Title" class="form-control" />
                    <br />
                    <label>Değer</label>
                    <input type="text" name="Value" class="form-control" />
                    <br />
                </div>
                <button type="submit" class="btn btn-primary">Ekle</button>
            </form>
        </div>
    </div>
</div>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/Template/assets/vendors/js/vendor.bundle.base.js"></script>

MvcWebUI/Views/Skill/Index.cshtml
@using Entities.Concrete
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description" style="font-size: 18px">Yetenek Listesi </p>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Değer</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Title</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar" style="width: @item.Value%" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100">@item.Value</div>
                                    </div>
                                </td>
                                <td><a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Sil</a></td>
                                <td><a asp-action="Update" asp-route-id="@item.Id" class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }

                    </tbody>
                </table>
                <a asp-action="Add" class="btn btn-outline-info">Yeni Yetenek Ekle</a>
            </div>
        </div>
    </div>
</div>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/Template/assets/vendors/js/vendor.bundle.base.js"></script>

MvcWebUI/Views/Skill/Update.cshtml
@model Entities.Concrete.Skill
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
<div class="card">
    <div class="card-body">
        <p class="card-description" style="font-size: 18px">Yetenek Güncelleme </p>

        @using (Html.BeginForm("Update", "Skill", FormMethod.Post))
        {
            <div class="mb-3">
                @Html.HiddenFor(x => x.Id)
                @Html.Label("Başlık")
                @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                <br />
                @Html.Label("Değer")
                @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
                <br />
            </div>
            <button type="submit" class="btn btn-primary">Güncelle</button>
        }
    </div>
</div>
</div>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/Template/assets/vendors/js/vendor.bundle.base.js"></script>